### PR TITLE
opt: `{legacy: true}` added

### PR DESCRIPTION
**Pull request by maraisr**
Ability to go `{legacy: true}` and support IE 5-7, Safari 1.X, and Netscape.

### CODE REVIEW

**Comment by iamvdo** [comment]
Hi.
Two things:
- Is `lodash.concat` and `lodash.foreach` required? I'm not a fan of using multiple dependencies
- Can you update README to add option and sample maybe ?

Thanks!

**Comment by maraisr** [comment]
Hey mate,

Yeah sure - so I ditched out the `lodash` deps!

Don't quite know why the mocha tests fail - feel free to leave the pr open till I get time to resolve the mocha tests, but i believe its working fine.

Cheers,
Marais

**Comment by maraisr** [comment]
Hey again mate - just fixed the tests. Their all passing now.

**Comment by maraisr** [comment]
@iamvdo Bump... Can I please get an indication if this is going to merged?

**Pull request merged**
