### PR TITLE
Upgrade to postcss@6 and devDeps

### PR DESCRIPTION
**Pull request by perrin4869**

### CODE REVIEW

**Comment by iamvdo** [comment]
Sorry for the delay. What's the point of `package-lock`? Is it necessary? How it's updated? (I never use this file before)

**Comment by perrin4869** [comment]
Thanks for the review!

`package-lock` is automatically generated by `npm@5` when you run `npm install` and I've been seeing many projects include it now. I'm not very knowledgeable about it, but it is automatically maintained by `npm@5`. As far as I understand, it makes builds more predictable, helping npm rebuild the dependency tree the exact same way across environments.

**Comment by perrin4869** [comment]
I could remove it if you're not comfortable with it yet

**Comment by iamvdo** [comment]
OK, thanks. Was using `npm@4`, so couldn't figure it out. Released as `postcss-opacity@5.0.0`.

**Pull request merged**
